### torch.nn.Module을 이용한 다중 선형회귀 모델

In [9]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

* 모델 코드

In [6]:
class MultipleLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3,1)

  def forward(self, x):
    return self.linear(x)

* 학습 코드

In [8]:
x_train = torch.FloatTensor([[73,80,75],
                             [93,88,93],
                             [89,91,80],
                             [96,98,100]])
y_train = torch.FloatTensor([152,185,180,196]).view(-1,1)

model = MultipleLinearRegressionModel()
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.4574, -0.4643, -0.5093]], requires_grad=True), Parameter containing:
tensor([-0.5603], requires_grad=True)]


In [10]:
optimizer = optim.SGD(model.parameters(), lr=1e-5)
nb_epochs = 1000
for epoch in range(nb_epochs+1):
  # 가설, 손실함수
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)

  # 경사하강법
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100==0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/1000 Cost: 93597.921875
Epoch  100/1000 Cost: 6.149569
Epoch  200/1000 Cost: 5.834129
Epoch  300/1000 Cost: 5.538378
Epoch  400/1000 Cost: 5.260834
Epoch  500/1000 Cost: 5.000278
Epoch  600/1000 Cost: 4.755471
Epoch  700/1000 Cost: 4.525442
Epoch  800/1000 Cost: 4.309029
Epoch  900/1000 Cost: 4.105368
Epoch 1000/1000 Cost: 3.913602


* 추론 코드

In [11]:
test_data = torch.FloatTensor([[73,66,70]])
prediction = model(test_data)
print(prediction)

tensor([[140.9175]], grad_fn=<AddmmBackward0>)
