### 선형회귀 복습

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [4]:
# 데이터셋 생성
x_train = torch.FloatTensor([1,2,3]).view(-1,1)
y_train = torch.FloatTensor([2,4,6]).view(-1,1)

# 모델 파라미터(W,b) 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b],lr=0.01)

nb_epochs = 1000  # 경사하강법 반복 횟수
for epoch in range(nb_epochs+1):
  # 가설, 손실함수
  hypo = x_train*W + b
  cost = torch.mean((hypo-y_train)**2)

  # 경사하강법
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100 == 0:
     print("Epoch {:4d}/{} W: {:3f}, b: {:3f} Cost: {:6f}".format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

  # 'cost function의 cost가 0이면 끝낸다'(학습 종료 조건 만족) 구현 -> 불확실함(내가 작성함)
  if cost == 0:
    break

Epoch    0/1000 W: 0.186667, b: 0.080000 Cost: 18.666666
Epoch  100/1000 W: 1.745691, b: 0.578072 Cost: 0.048171
Epoch  200/1000 W: 1.800099, b: 0.454421 Cost: 0.029767
Epoch  300/1000 W: 1.842860, b: 0.357217 Cost: 0.018394
Epoch  400/1000 W: 1.876473, b: 0.280805 Cost: 0.011366
Epoch  500/1000 W: 1.902897, b: 0.220738 Cost: 0.007024
Epoch  600/1000 W: 1.923668, b: 0.173520 Cost: 0.004340
Epoch  700/1000 W: 1.939996, b: 0.136403 Cost: 0.002682
Epoch  800/1000 W: 1.952832, b: 0.107225 Cost: 0.001657
Epoch  900/1000 W: 1.962921, b: 0.084289 Cost: 0.001024
Epoch 1000/1000 W: 1.970853, b: 0.066259 Cost: 0.000633


Q. zero_grad()를 해주지 않는다면?

A. 미분값이 계속 누적되어 더해짐 (중첩됨)

In [15]:
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
  z = 3*w
  z.backward()
  print(f'수식을 w로 미분한 값 : {w.grad}')

수식을 w로 미분한 값 : 3.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 9.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 15.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 21.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 27.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 33.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 39.0
수식을 w로 미분한 값 : 42.0
수식을 w로 미분한 값 : 45.0
수식을 w로 미분한 값 : 48.0
수식을 w로 미분한 값 : 51.0
수식을 w로 미분한 값 : 54.0
수식을 w로 미분한 값 : 57.0
수식을 w로 미분한 값 : 60.0
수식을 w로 미분한 값 : 63.0


Q. 왜 w.item()으로 출력하면 출력값의 변화가 없지?

A. [머신러닝 학습 코드 내에서] optimizer.step() : optimizer에 전달된 파라미터 W,b 값을 업데이트

-> but 아래 코드에서는 w를 업데이트 하는 업데이트하는 step()이 없기 때문에 w.item()은 그대로인 것임.

In [20]:
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
  z = 3*w
  z.backward()
  print(f'수식을 w로 미분한 값 : {w.item()}')

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 2.0


Q. optimizer.zero_grad()는 무엇을 초기화하는 것인가?

A. W.grad, b.grad와 같이 optimizer가 관리하는 모델의 파라미터에 대한 그래디언트를 0(None)으로 초기화함.

In [21]:
# 데이터셋 생성
x_train = torch.FloatTensor([1,2,3]).view(-1,1)
y_train = torch.FloatTensor([2,4,6]).view(-1,1)

# 모델 파라미터(W,b) 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b],lr=0.01)

nb_epochs = 1000  # 경사하강법 반복 횟수
for epoch in range(nb_epochs+1):
  # 가설, 손실함수
  hypo = x_train*W + b
  cost = torch.mean((hypo-y_train)**2)

  # 경사하강법
  if epoch%100 == 0:
    print(f"초기화 전 그래디언트 값 : {W.grad}, {b.grad}")
  optimizer.zero_grad()
  if epoch%100 == 0:
    print(f"초기화 후 그래디언트 값 : {W.grad}, {b.grad}")
  cost.backward()
  optimizer.step()

  if epoch%100 == 0:
     print("Epoch {:4d}/{} W: {:3f}, b: {:3f} Cost: {:6f}".format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

  # 'cost function의 cost가 0이면 끝낸다'(학습 종료 조건 만족) 구현 -> 불확실함(내가 작성함)
  if cost == 0:
    break

초기화 전 그래디언트 값 : None, None
초기화 후 그래디언트 값 : None, None
Epoch    0/1000 W: 0.186667, b: 0.080000 Cost: 18.666666
초기화 전 그래디언트 값 : tensor([-0.0616]), tensor([0.1396])
초기화 후 그래디언트 값 : None, None
Epoch  100/1000 W: 1.745691, b: 0.578072 Cost: 0.048171
초기화 전 그래디언트 값 : tensor([-0.0483]), tensor([0.1098])
초기화 후 그래디언트 값 : None, None
Epoch  200/1000 W: 1.800099, b: 0.454421 Cost: 0.029767
초기화 전 그래디언트 값 : tensor([-0.0380]), tensor([0.0863])
초기화 후 그래디언트 값 : None, None
Epoch  300/1000 W: 1.842860, b: 0.357217 Cost: 0.018394
초기화 전 그래디언트 값 : tensor([-0.0298]), tensor([0.0678])
초기화 후 그래디언트 값 : None, None
Epoch  400/1000 W: 1.876473, b: 0.280805 Cost: 0.011366
초기화 전 그래디언트 값 : tensor([-0.0235]), tensor([0.0533])
초기화 후 그래디언트 값 : None, None
Epoch  500/1000 W: 1.902897, b: 0.220738 Cost: 0.007024
초기화 전 그래디언트 값 : tensor([-0.0184]), tensor([0.0419])
초기화 후 그래디언트 값 : None, None
Epoch  600/1000 W: 1.923668, b: 0.173520 Cost: 0.004340
초기화 전 그래디언트 값 : tensor([-0.0145]), tensor([0.0329])
초기화 후 그래디언트 값 : None, None


### 다중 선형회귀

데이터셋 편하게 설정하는 예진이의 방법
* 입력값들 1차원 텐서로 나열하기
* view()와 -1 인자 이용 -> 원하는 size 만들기

In [31]:
x_train = torch.FloatTensor([[73,80,75],
                             [93,88,93],
                             [89,91,80],
                             [96,98,100]])
x = x_train.view(-1)
print(x)
x.view(-1,3)  # x_train과 동일함

tensor([ 73.,  80.,  75.,  93.,  88.,  93.,  89.,  91.,  80.,  96.,  98., 100.])


tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  80.],
        [ 96.,  98., 100.]])

* 학습

In [34]:
# 데이터셋 생성
x_train = torch.FloatTensor([[73,80,75],
                             [93,88,93],
                             [89,91,80],
                             [96,98,100]])
y_train = torch.FloatTensor([152,185,180,196]).view(-1,1)

# 모델 파라미터 초기화
W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs+1):
  # 가설, 손실함수
  hypo = x_train.matmul(W) + b
  cost = torch.mean((hypo-y_train)**2)

  # 경사하강법
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  w_list = W.view(-1).tolist()
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} w1: {:.3f}, w2: {:.3f}, w3: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(epoch, nb_epochs, w_list[0], w_list[1], w_list[2], b.item(), cost.item()))

Epoch    0/1000 w1: 0.316, w2: 0.320, w3: 0.313, b: 0.004 Cost: 32036.250000
Epoch  100/1000 w1: 0.684, w2: 0.688, w3: 0.652, b: 0.008 Cost: 6.938233
Epoch  200/1000 w1: 0.694, w2: 0.693, w3: 0.637, b: 0.008 Cost: 6.573693
Epoch  300/1000 w1: 0.704, w2: 0.698, w3: 0.622, b: 0.008 Cost: 6.232265
Epoch  400/1000 w1: 0.714, w2: 0.702, w3: 0.608, b: 0.008 Cost: 5.912263
Epoch  500/1000 w1: 0.724, w2: 0.706, w3: 0.594, b: 0.008 Cost: 5.612178
Epoch  600/1000 w1: 0.733, w2: 0.710, w3: 0.581, b: 0.008 Cost: 5.330629
Epoch  700/1000 w1: 0.743, w2: 0.713, w3: 0.568, b: 0.008 Cost: 5.066350
Epoch  800/1000 w1: 0.752, w2: 0.717, w3: 0.555, b: 0.008 Cost: 4.818101
Epoch  900/1000 w1: 0.761, w2: 0.720, w3: 0.543, b: 0.008 Cost: 4.584816
Epoch 1000/1000 w1: 0.769, w2: 0.722, w3: 0.532, b: 0.008 Cost: 4.365375


* 추론

In [35]:
test_data = torch.FloatTensor([73,66,70]).view(1,-1)
prediction = test_data.matmul(W) + b
print(prediction)

tensor([[141.0700]], grad_fn=<AddBackward0>)
