### 선형 회귀 (Linear Regression)

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

* 데이터셋 생성

In [2]:
# 학습 데이터셋 구성
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])
print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


* 모델 초기화

In [3]:
# 가중치, 편향 생성
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
print(W)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [4]:
# 가설 수립
hypo = x_train*W + b
print(hypo)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [5]:
# 비용함수 선언
cost = torch.mean((hypo - y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


* optimizer 설정

In [6]:
optimizer = optim.SGD([W, b], lr=0.01)
nb_epochs = 1000 # 1000만큼 경사하강법 반복

* 학습

In [7]:
for epoch in range(nb_epochs + 1):
  # 가설, 손실함수
  hypo = x_train*W + b
  cost = torch.mean((hypo - y_train)**2)

  # 경사하강법
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 100번마다 로그 출력
  if epoch%100 == 0:
     print("Epoch {:4d}/{} W: {:3f}, b: {:3f} Cost: {:6f}".format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0/1000 W: 0.186667, b: 0.080000 Cost: 18.666666
Epoch  100/1000 W: 1.745691, b: 0.578072 Cost: 0.048171
Epoch  200/1000 W: 1.800099, b: 0.454421 Cost: 0.029767
Epoch  300/1000 W: 1.842860, b: 0.357217 Cost: 0.018394
Epoch  400/1000 W: 1.876473, b: 0.280805 Cost: 0.011366
Epoch  500/1000 W: 1.902897, b: 0.220738 Cost: 0.007024
Epoch  600/1000 W: 1.923668, b: 0.173520 Cost: 0.004340
Epoch  700/1000 W: 1.939996, b: 0.136403 Cost: 0.002682
Epoch  800/1000 W: 1.952832, b: 0.107225 Cost: 0.001657
Epoch  900/1000 W: 1.962921, b: 0.084289 Cost: 0.001024
Epoch 1000/1000 W: 1.970853, b: 0.066259 Cost: 0.000633


* 추론

In [8]:
test_data = torch.FloatTensor([[4]])
prediction = test_data*W + b
print(prediction)

tensor([[7.9497]], grad_fn=<AddBackward0>)
