### PyTorch에서 텐서 다루기

In [ ]:
import torch

t = torch.tensor([0,1,2,3,4,5,6])
print(t)  # 텐서 출력
print(t.dim())  # rank(차원)
print(t.shape)  # shape(차원의 크기)
print(t.size()) # shape
print(t.dtype)  # data type

tensor([0, 1, 2, 3, 4, 5, 6])
1
torch.Size([7])
torch.Size([7])
torch.int64


Q. shape와 size()의 차이점은? (미해결)

In [ ]:
q = torch.tensor([[1,2,3],[4,5,6]])
print(q.shape)
print(q.size())

torch.Size([2, 3])
torch.Size([2, 3])


* 1D 텐서 다루기

In [ ]:
t = torch.DoubleTensor([0,1,2,3,4,5,6])
print(t)
print(t.shape)
print(t.dtype)

tensor([0., 1., 2., 3., 4., 5., 6.], dtype=torch.float64)
torch.Size([7])
torch.float64


In [ ]:
t = torch.FloatTensor([0,1,2,3,4,5,6])
print(t)
print(t.shape)
print(t.dtype)

tensor([0., 1., 2., 3., 4., 5., 6.])
torch.Size([7])
torch.float32


In [ ]:
print(t[0], t[1], t[2])
print(t[2:5], t[4:-1])
print(t[:2],t[3:])

tensor(0.) tensor(1.) tensor(2.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


* 2D 텐서 다루기

In [ ]:
t = torch.FloatTensor([[1,2,3],
                      [4,5,6],
                      [7,8,9],
                      [10,11,12]])

print(t)
print(t.shape)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([4, 3])


In [ ]:
print(t[:,1])
print(t[:,1].size())
print(t[:][[1]])

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[4., 5., 6.]])


In [ ]:
print(t[:,:-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


* 브로드캐스팅(Broadcasting)

In [ ]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1.shape, m2.shape)
print(m1+m2)

torch.Size([1, 2]) torch.Size([1, 2])
tensor([[5., 5.]])


In [ ]:
# 브로드캐스팅 예1: vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1.shape, m2.shape)
print(m1 + m2)

torch.Size([1, 2]) torch.Size([1])
tensor([[4., 5.]])


In [ ]:
# 브로드캐스팅 예2: vector + vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1.shape, m2.shape)
print(m1 + m2)

torch.Size([1, 2]) torch.Size([2, 1])
tensor([[4., 5.],
        [5., 6.]])


In [34]:
m1 = torch.FloatTensor([[1,2]])
print(3 + m1)
print(torch.tensor([3]) + m1)

tensor([[4., 5.]])
tensor([[4., 5.]])


* element-wise multiplication

In [ ]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[4,5],[6,7]])

print(m1 * m2)
print(m1.mul(m2))

tensor([[ 4., 10.],
        [18., 28.]])
tensor([[ 4., 10.],
        [18., 28.]])


* matrix multiplication (행렬곱)

In [ ]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1.shape, m2.shape)
print(m1.matmul(m2))
print(m2.matmul(m1))

torch.Size([2, 2]) torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


RuntimeError: ignored

* 평균 구하기

In [ ]:
t = torch.FloatTensor([[1,2,3],[4,5,6]])
print(t.mean())
print(t.mean().item())

tensor(3.5000)
3.5


In [ ]:
print(t.shape)
print(t.mean(dim=0))
print(t.mean(dim=0).shape)

torch.Size([2, 3])
tensor([2.5000, 3.5000, 4.5000])
torch.Size([3])


In [ ]:
print(t.shape)
print(t.mean(dim=1))
print(t.mean(dim=1).shape)
print(t.mean(dim=-1))

torch.Size([2, 3])
tensor([2., 5.])
torch.Size([2])
tensor([2., 5.])


* 합계 구하기

In [ ]:
t = torch.FloatTensor([[1,2,3],[4,5,6]])  # shape:(2,3)
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(21.)
tensor([5., 7., 9.])
tensor([ 6., 15.])
tensor([ 6., 15.])


* 최댓값 및 최댓값의 위치 구하기

In [ ]:
print(t.max())
print(t.max(dim=0))
print(f"Values: {t.max(dim=0)[0]}")
print(f"Indices: {t.max(dim=0)[1]}")

tensor(6.)
torch.return_types.max(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))
Values: tensor([4., 5., 6.])
Indices: tensor([1, 1, 1])


In [ ]:
t = torch.FloatTensor([[0,1,2],
                      [3,4,5],
                      [6,7,8]])
print(t.max())
print(t.max(dim=0))

tensor(8.)
torch.return_types.max(
values=tensor([6., 7., 8.]),
indices=tensor([2, 2, 2]))


* view - 텐서 shape 변경하기

In [ ]:
# 3차원 텐서 생성
t = torch.FloatTensor([[[0,1,2],
                        [3,4,5]],
                       [[6,7,8],
                        [9,10,11]]])
print(t.shape)

torch.Size([2, 2, 3])


In [ ]:
print(t.view(4,3))
print(t.view(2,1,6))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.]],

        [[ 6.,  7.,  8.,  9., 10., 11.]]])


In [ ]:
print(t.view(-1,2,3))
print(t.view(2,2,3))

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [ ]:
print(t.view(-1,5)) # 원소 개수 유지 안되니까 오류나겠지?

RuntimeError: ignored