### 로지스틱 회귀 - 이진 분류

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

* 모델

In [ ]:
class LogisticRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(2, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    return self.sigmoid(self.linear(x))

* 학습

In [ ]:
x_train = torch.FloatTensor([[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]])
y_train = torch.FloatTensor([0,0,0,1,1,1]).view(-1,1)

model = LogisticRegression()

optimizer = optim.SGD(model.parameters(), lr=1e-1)
nb_epochs = 1000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)
  cost = F.binary_cross_entropy(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100 == 0:
    predicted_class = prediction >= torch.FloatTensor([0.5])
    correct_prediction = predicted_class.float() == y_train
    accuracy = correct_prediction.sum().item() / len(correct_prediction)
    print('Epoch {:4d}/{} Cost: {:.6f} Accuracy: {:2.2f}%'.format(epoch, nb_epochs, cost, accuracy*100))

Epoch    0/1000 Cost: 1.107901 Accuracy: 16.67%
Epoch  100/1000 Cost: 0.442916 Accuracy: 83.33%
Epoch  200/1000 Cost: 0.369840 Accuracy: 83.33%
Epoch  300/1000 Cost: 0.317096 Accuracy: 83.33%
Epoch  400/1000 Cost: 0.275972 Accuracy: 83.33%
Epoch  500/1000 Cost: 0.243450 Accuracy: 100.00%
Epoch  600/1000 Cost: 0.217364 Accuracy: 100.00%
Epoch  700/1000 Cost: 0.196120 Accuracy: 100.00%
Epoch  800/1000 Cost: 0.178563 Accuracy: 100.00%
Epoch  900/1000 Cost: 0.163852 Accuracy: 100.00%
Epoch 1000/1000 Cost: 0.151371 Accuracy: 100.00%


* 추론

In [ ]:
test_data = torch.FloatTensor([[5,5],[1,4]])  # 각각 class가 1, 0임
prediction = model(test_data)
print(prediction)

tensor([[0.9697],
        [0.0551]], grad_fn=<SigmoidBackward0>)


### 소프트맥스 회귀 - 다중 클래스 분류

* 모델

In [ ]:
class SoftmaxRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(4, 3)

  def forward(self, x):
    return self.linear(x)

* 학습

In [ ]:
x_train = torch.FloatTensor([[6.3,3.3,6.0,2.5],
                             [5.8,2.7,5.1,1.9],
                             [7.1,3.0,5.9,2.1],
                             [5.1,3.5,1.4,0.2],
                             [4.9,3.0,1.4,0.2],
                             [4.7,3.2,1.3,0.2],
                             [7.0,3.2,4.7,1.4],
                             [6.4,3.2,4.5,1.5],
                             [6.9,3.1,4.9,1.5]])
y_train = torch.LongTensor([0,0,0,1,1,1,2,2,2])

model = SoftmaxRegression()

optimizer = optim.SGD(model.parameters(), lr=1e-1)
nb_epochs = 1000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)
  cost = F.cross_entropy(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100 == 0:
    print(F.softmax(prediction, dim=1))
    correct_prediction = torch.argmax(prediction, 1) == y_train
    accuracy = correct_prediction.float().mean().item()
    print("Epoch {:4d}/{} Cost: {:.6f} Accuracy: {:2.2f}%".format(epoch, nb_epochs, cost.item(), accuracy*100))

tensor([[0.8909, 0.1061, 0.0030],
        [0.8819, 0.1124, 0.0057],
        [0.9123, 0.0854, 0.0023],
        [0.8490, 0.1348, 0.0163],
        [0.8421, 0.1370, 0.0209],
        [0.8341, 0.1441, 0.0218],
        [0.9101, 0.0868, 0.0031],
        [0.8951, 0.1005, 0.0044],
        [0.9086, 0.0882, 0.0032]], grad_fn=<SoftmaxBackward0>)
Epoch    0/1000 Cost: 2.579061 Accuracy: 33.33%
tensor([[8.1884e-01, 1.8098e-03, 1.7935e-01],
        [6.2365e-01, 6.4758e-03, 3.6988e-01],
        [5.0452e-01, 4.1154e-03, 4.9136e-01],
        [4.5388e-04, 9.0949e-01, 9.0052e-02],
        [1.1808e-03, 8.3670e-01, 1.6212e-01],
        [9.0072e-04, 8.8527e-01, 1.1383e-01],
        [9.8206e-02, 5.4002e-02, 8.4779e-01],
        [1.6465e-01, 6.3019e-02, 7.7233e-01],
        [1.5657e-01, 3.4026e-02, 8.0940e-01]], grad_fn=<SoftmaxBackward0>)
Epoch  100/1000 Cost: 0.265125 Accuracy: 100.00%
tensor([[9.5609e-01, 2.0323e-04, 4.3702e-02],
        [8.2847e-01, 1.5368e-03, 1.7000e-01],
        [7.4180e-01, 9.4339e-04, 

* 원리 이해 도움

In [ ]:
x_train = torch.FloatTensor([[6.3,3.3,6.0,2.5],
                             [5.8,2.7,5.1,1.9],
                             [7.1,3.0,5.9,2.1],
                             [5.1,3.5,1.4,0.2],
                             [4.9,3.0,1.4,0.2],
                             [4.7,3.2,1.3,0.2],
                             [7.0,3.2,4.7,1.4],
                             [6.4,3.2,4.5,1.5],
                             [6.9,3.1,4.9,1.5]])
y_train = torch.LongTensor([0,0,0,1,1,1,2,2,2])

model = SoftmaxRegression()

optimizer = optim.SGD(model.parameters(), lr=1e-1)
nb_epochs = 1000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)
  cost = F.cross_entropy(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100 == 0:
    correct_prediction = torch.argmax(prediction, 1)  == y_train
    print(correct_prediction)
    print(correct_prediction.float())
    accuracy = correct_prediction.float().mean().item()

tensor([False, False, False,  True,  True,  True, False, False, False])
tensor([0., 0., 0., 1., 1., 1., 0., 0., 0.])
tensor([ True,  True, False,  True,  True,  True,  True,  True,  True])
tensor([1., 1., 0., 1., 1., 1., 1., 1., 1.])
tensor([True, True, True, True, True, True, True, True, True])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([True, True, True, True, True, True, True, True, True])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([True, True, True, True, True, True, True, True, True])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([True, True, True, True, True, True, True, True, True])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([True, True, True, True, True, True, True, True, True])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([True, True, True, True, True, True, True, True, True])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([True, True, True, True, True, True, True, True, True])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([Tr

* 테스트