### squeeze

In [2]:
import torch

In [3]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape) # size:[3,1]

print(ft.squeeze()) # [3,1] -> [3]
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


### unsqueeze

In [8]:
ft = torch.tensor([0,1,2])
print(ft)
print(ft.shape)

print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([0, 1, 2])
torch.Size([3])
tensor([[0, 1, 2]])
torch.Size([1, 3])


In [9]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0],
        [1],
        [2]])
torch.Size([3, 1])


### Type casting

In [11]:
lt = torch.LongTensor([1,2,3,4])
print(lt)
print(lt.dtype)

print(lt.float())
print(lt.double())

tensor([1, 2, 3, 4])
torch.int64
tensor([1., 2., 3., 4.])
tensor([1., 2., 3., 4.], dtype=torch.float64)


### Concatenate

In [13]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])
print(x.shape, y.shape)

print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=0).shape)

print(torch.cat([x,y], dim=1))
print(torch.cat([x,y], dim=1).shape)

torch.Size([2, 2]) torch.Size([2, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
torch.Size([4, 2])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
torch.Size([2, 4])


In [14]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])
z = torch.FloatTensor([[9,10],[11,12]])
print(x.shape)

print(torch.cat([x,y,z], dim=0))
print(torch.cat([x,y,z], dim=0).shape)

print(torch.cat([x,y,z], dim=1))
print(torch.cat([x,y,z], dim=1).shape)

torch.Size([2, 2])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
torch.Size([6, 2])
tensor([[ 1.,  2.,  5.,  6.,  9., 10.],
        [ 3.,  4.,  7.,  8., 11., 12.]])
torch.Size([2, 6])


In [16]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8],[9,10]])
print(x.shape, y.shape)

print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=0).shape)

print(torch.cat([x,y], dim=1))
print(torch.cat([x,y], dim=1).shape)

torch.Size([2, 2]) torch.Size([3, 2])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
torch.Size([5, 2])


RuntimeError: ignored

### ones_like, zeros_like

In [17]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### ones, zeros

In [19]:
print(torch.ones(2,3))
print(torch.zeros(3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
