### Tensor란?

Q. **데이터가 차원을 갖게 되면 해당 차원의 크기 또한 존재함** 에서 해당 차원의 크기는 n차원의 n을 의미하는 것이 아니라 numpy의 shape 속성 값을 의미하는 것인가?

In [2]:
import numpy as np

# 데이터 data_a가 1차원의 차원을 갖게 되면 해당 차원의 크기 또한 존재한다.
data_a = np.array([0,1,2])  # data_a:vector
print(data_a.shape)

# 데이터 data_b가 2차원의 차원을 갖게 되면 해당 차원의 크기 또한 존재한다.
data_b = np.array([[0,1,2],[3,4,5]])  # data_b:matrix
print(data_b.shape)

(3,)
(2, 3)


### numpy array

In [3]:
import numpy as np

a = np.array([1,2,3]) # rank(배열의 차원):1
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]]) # rank:2
print(b.shape)
print(b[0,0],b[0,1],b[0,2])
print(b[0][0],b[0][1],b[0][2])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 3
1 2 3


In [7]:
# 추가)
# shape로 알 수 있는 것

# 1. 몇 차원인지 -> len(튜플)
print(len(a.shape))
print(len(b.shape))

# 2, 차원의 크기 -> shape
print(a.shape)
print(b.shape)

1
2
(3,)
(2, 3)


### numpy dtype

In [12]:
# numpy array의 type 강제 지정하기

x = np.array([1,2])
print(x.dtype)
print(x)

x = np.array([1.0,2.0])
print(x.dtype)
print(x)

x = np.array([1,2], dtype=np.int64)
print(x.dtype)
print(x)

x = np.array([1,2], dtype=np.float64)
print(x.dtype)
print(x)

int64
[1 2]
float64
[1. 2.]
int64
[1 2]
float64
[1. 2.]


### numpy matrix operations

In [13]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# 요소별 합
print(x+y)
print(np.add(x,y))

# 요소별 차
print(x-y)
print(np.subtract(x,y))
print(np.subtract(y,x)) # 값 다를 것임

# 요소별 곱 : 행렬의 요소끼리 곱한 결과!!
print(x*y)
print(np.multiply(x,y))
print(np.multiply(y,x)) # 값 같을 것임 -> why? 요소끼리의 곱이니까

# 요소별 나눗셈
print(x/y)
print(np.divide(x,y))
print(np.divide(y,x)) # 값 다를 것임

# 요소별 제곱근 : 루트 씌움
print(np.sqrt(x))
print(np.sqrt(y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[4. 4.]
 [4. 4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[5.         3.        ]
 [2.33333333 2.        ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


dot 연산

In [14]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

v = np.array([9,10])
w = np.array([11,12])

# 벡터의 내적 : 같은 index끼리 곱해서 더하기
print(v.dot(w))
print(np.dot(v,w))

# 행렬과 벡터의 곱
print(x.dot(v))
print(np.dot(x,v))

# 추가) 벡터와 행렬의 곱
print(v.dot(x))
print(np.dot(v,x))

# 행렬곱
print(x.dot(y))
print(np.dot(x,y))

219
219
[29. 67.]
[29. 67.]
[39. 58.]
[39. 58.]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]
